"""
Weather Dashboard - Pure framework-generated reference app.

This app is COMPLETELY generated by AI agents - no manual coding.
"""
import asyncio
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..')))

from build_my_startup.pipelines.adaptive_build import AdaptiveBuildConfig, AdaptiveBuildPipeline
from build_my_startup.paths import default_app_paths

OUTPUT_DIR, TEMPLATES_DIR, STATIC_DIR = default_app_paths(__file__)

# Simple, achievable app idea
STARTUP_IDEA = """
Build a Weather Dashboard web app.

Users enter a city name and see:
- Current temperature
- Weather condition (sunny, rainy, etc.)
- 5-day forecast

Technical requirements:
- Flask backend
- Use a free weather API (OpenWeatherMap or weatherapi.com)
- Modern, clean UI with weather icons
- Responsive design
- Store recent searches in JSON file
- Run on Mac, port 5003

Keep it simple - just a clean MVP.
"""

async def main():
    print("=" * 80)
    print("🌤️  Building Weather Dashboard - Framework-Generated App")
    print("=" * 80)
    print(f"\n📁 Output: {OUTPUT_DIR}\n")
    
    # Use config.json defaults, keep it simple and fast
    config = AdaptiveBuildConfig(
        output_dir=OUTPUT_DIR,
        templates_dir=TEMPLATES_DIR,
        static_dir=STATIC_DIR,
        min_files=3,  # Keep minimal
        max_files=6,  # Not too many
        timeout=300,  # 5 minutes max
        ideation_timeout=45  # Fast ideation
    )
    
    print("🚀 Starting build... (est. 3-5 minutes)\n")
    
    pipeline = AdaptiveBuildPipeline(config)
    
    try:
        result = await pipeline.run_adaptive_build(
            description=STARTUP_IDEA,
            target_platform="macOS",
            tech_preferences={"framework": "Flask", "port": 5003}
        )
        
        print("\n" + "=" * 80)
        print("✅ BUILD COMPLETE!")
        print("=" * 80)
        print(f"Generated: {result['generated']} files")
        print(f"Saved: {result['saved']} files")
        print(f"Tests: {len(result['tests'])}")
        print(f"\n📁 {OUTPUT_DIR}")
        
        if result.get('inferred_tasks'):
            print(f"\n🧠 Components built:")
            for task in result['inferred_tasks']:
                print(f"   • {task['task']}")
        
        print(f"\n🎉 Run: cd {OUTPUT_DIR} && python app.py")
        return result
        
    except Exception as e:
        print(f"\n❌ Build failed: {e}")
        import traceback
        traceback.print_exc()
        raise

if __name__ == "__main__":
    result = asyncio.run(main())
    sys.exit(0 if result.get('saved', 0) > 0 else 1)

